# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
            ('cases', '0003_load_ipra_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=20)),
                ('payee', models.CharField(max_length=100)),
                ('payment', models.IntegerField()),
                ('fees_costs', models.IntegerField()),
                ('primary_cause', models.CharField(max_length=50)),
                ('primary_cause_edited', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('disposition', models.CharField(max_length=50)),
                ('date_paid', models.DateField()),
                ('misconduct', models.BooleanField()),
                ('disposition_true', models.CharField(max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
        ),
    ]
