# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 18:31
from __future__ import unicode_literals
from django.db import migrations
from settlements.settings import BASE_DIR 
import unicodecsv as csv
from cases.models import Case

### START CONFIG ###
narrative_file_name = BASE_DIR + '/data/20160620_migration/narratives.csv'
### END CONFIG ###

narrative_file = open(narrative_file_name)
narrative_csv  = csv.DictReader(narrative_file)


def add_narratives(apps,schema_editor):
    for row in narrative_csv:
        case = Case.objects.get(id=row['case_id'])
        case.narrative = row['narrative']
        case.save()



class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_load_payments_again'),
    ]

    operations = [
            migrations.RunPython(add_narratives)
    ]
