# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_first_name', models.CharField(max_length=20)),
                ('cop_middle_initial', models.CharField(max_length=5)),
                ('cop_last_name', models.CharField(max_length=20)),
                ('badge_no', models.CharField(max_length=10)),
                ('case_no', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=50)),
                ('officer_atty', models.CharField(max_length=100)),
                ('officer_atty_firm', models.CharField(max_length=100)),
                ('entered_by', models.CharField(max_length=20)),
                ('entered_when', models.DateField(null=True)),
                ('fact_checked_by', models.CharField(max_length=20)),
                ('fact_checked_when', models.DateField(null=True)),
                ('matched_by', models.CharField(max_length=10)),
                ('matched_when', models.DateTimeField(null=True)),
                ('note', models.CharField(max_length=1000)),
                ('flag', models.NullBooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_init', models.CharField(max_length=5)),
                ('sex', models.CharField(max_length=5)),
                ('race', models.CharField(max_length=30)),
                ('dob_year', models.IntegerField(null=True)),
                ('current_age', models.IntegerField(null=True)),
                ('status', models.BooleanField()),
                ('appointed_date', models.DateField(null=True)),
                ('position_code', models.CharField(max_length=5)),
                ('position_desc', models.CharField(max_length=40)),
                ('cpd_unit', models.CharField(max_length=5)),
                ('cpd_unit_desc', models.CharField(max_length=55)),
                ('resignation_date', models.DateField(null=True)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CopStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=10)),
                ('cop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cops.Cop')),
            ],
        ),
        migrations.CreateModel(
            name='IPRACop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop_first_name', models.CharField(max_length=20)),
                ('cop_middle_initial', models.CharField(max_length=5)),
                ('cop_last_name', models.CharField(max_length=20)),
                ('badge_no', models.CharField(max_length=10)),
                ('cr_no', models.IntegerField()),
                ('finding', models.CharField(max_length=10)),
                ('discipline_code', models.CharField(max_length=5)),
                ('discipline', models.CharField(max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.IPRACase')),
                ('cop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cops.Cop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casecop',
            name='cop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cops.Cop'),
        ),
    ]
