# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 17:40
from __future__ import unicode_literals
from django.db import migrations
import csv
from cops.models import Cop, CaseCop, CopStar
from cases.models import Case
from cops.utils.loaders import case_cop_loader
from utils.types import parse_str_date, intify
from settlements.settings import BASE_DIR


def load_all_sworn_employees(apps, schema_editor):
    """
    load cops data
    """
    employees_file_path = BASE_DIR + '/cops/migrations/all_sworn_employees.csv'
    employees_file      = open(employees_file_path)
    employees_csv       = csv.DictReader(employees_file)
    dated_employees    = []
    for employee in employees_csv:
        employee['DOBYEAR']        = intify(employee['DOBYEAR'])
        employee['CURRAGE']        = intify(employee['CURRAGE'])
        employee['APPOINTED_DATE'] = parse_str_date(employee['APPOINTED_DATE'])
        employee['RESIGNATION_DATE'] = parse_str_date(employee['RESIGNATION_DATE'])
        dated_employees.append(employee)
    # for sorting
    employees_without_start   = sorted([x for x in dated_employees if not x['APPOINTED_DATE']], key = lambda x: (x['LAST_NME'], x['FIRST_NME']))
    employees_sorted_by_start = sorted([x for x in dated_employees if x['APPOINTED_DATE']], key = lambda x: (x['APPOINTED_DATE'], x['LAST_NME'], x['FIRST_NME']))
    employees_sorted = employees_without_start + employees_sorted_by_start 
    for employee in employees_sorted:
        try:
            cop = Cop.objects.create(
                                     last_name        = employee['LAST_NME'],
                                     first_name       = employee['FIRST_NME'],
                                     middle_init      = employee['MIDDLE_INITIAL'],
                                     sex              = employee['SEX_CODE_CD'],
                                     race             = employee['RACE'],
                                     dob_year         = employee['DOBYEAR'],
                                     current_age      = employee['CURRAGE'],
                                     status           = employee['STATUS_I'],
                                     appointed_date   = employee['APPOINTED_DATE'],
                                     position_code    = employee['EMPLOYEE_POSITION_CD'],
                                     position_desc    = employee['DESCR'],
                                     cpd_unit         = employee['CPD_UNIT_ASSIGNED_NO'],
                                     cpd_unit_desc    = employee['UNITDESCR'],
                                     resignation_date = employee['RESIGNATION_DATE'],
                                    )
            cop.slug = '_'.join([str(x) for x in (cop.last_name, cop.first_name, cop.middle_init, cop.race, cop.dob_year, cop.appointed_date)])
            cop.save()
        except Exception, e:
            print e
            import ipdb; ipdb.set_trace()
        stars = [employee[x] for x in ('STAR1','STAR2','STAR3','STAR4','STAR5','STAR6','STAR7','STAR8','STAR9','STAR10') if employee[x]]
        for star in stars:
            copstar = CopStar.objects.create(
                                             cop=cop,
                                             star=star
                                            )
            copstar.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_all_sworn_employees)
    ]
