# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 16:09
from __future__ import unicode_literals
from django.db import migrations
from cops.models import IPRACop
from datetime import datetime

def make_matches(apps,schema_editor):
    """
    automatically
    match cops with algorithm
    and mark auto-matched
    """
    ics = list(IPRACop.objects.all())
    total = len(ics)
    counter = 0
    for ic in ics:
        counter += 1
        print counter, '/', total
        qual_matches = ic.qualify_matches()['probable']
        if len(qual_matches) == 1:
            print 'match found for ic.id', ic.id
            ic.cop = qual_matches[0]
            ic.matched_by = 'auto'
            ic.matched_when = datetime.now()
            ic.flag = True
            ic.save()
        else:
            print 'no match found for ic.id', ic.id


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0005_auto_20160512_1849'),
    ]

    operations = [
            migrations.RunPython(make_matches)
    ]
