# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0008_ipracop_civil_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='cop',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
