# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 17:40
from __future__ import unicode_literals
from django.db import migrations
import unicodecsv as csv
from cops.models import Cop
from settlements.settings import BASE_DIR

### CONFIG START ###
update_file_name = BASE_DIR + '/data/20160620_migration/cops.csv'
### CONFIG END ###

update_file = open(update_file_name)
update_csv  = csv.DictReader(update_file)

def update_cop_notes(apps, schema_editor):
    for row in update_csv:
        cop       = Cop.objects.get(id=int(row['id']))
        cop.notes = row['notes']
        cop.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cops', '0010_cop_notes'),
    ]

    operations = [
        migrations.RunPython(update_cop_notes)
    ]
